### ISSUE TITLE
Works great, how about WP8 compatibility?

### ISSUE THREAD

**Issue by andreszs** [mohamed-salah/phonegap-backbutton-plugin#3]
Can someone please tell me how to implement it for WP8? That would be great.

**Comment by mohamed-salah** [comment]
sorry but for now there is no plan to implement for WP8 
you can learn from there http://docs.phonegap.com/en/edge/guide_platforms_wp8_plugin.md.html#Windows%20Phone%208%20Plugins
and of course you must to be good in c#
